# Generated by Django 5.2.7 on 2025-10-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A brief title for the milestone.', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what was learned or achieved.')),
                ('date_achieved', models.DateField(help_text='The date this milestone was completed.')),
            ],
        ),
    ]
